#!/bin/sh

case "$1" in 
	start)
		echo "Loading drivers and modules"
		scull_load
		module_load faulty
		modprobe hello
		;;
	stop)
		echo "Unloading drivers and modules"
		scull_unload
		module_unload faulty
		rmmod hello
		;;
	*)
		echo "usage: $0 {start|stop}"
	exit 1
esac

exit 0
	
