#!/bin/sh
set -e

NAME=lddmodules
case "$1" in 
	start)
		echo "Loading drivers and modules"
		modprobe hello
		module_load faulty
		scull_load
		;;
	stop)
		echo "Unloading drivers and modules"
		rmmod hello
        module_unload faulty
        scull_unload
		;;
	*)
		echo "usage: $0 {start|stop}"
	exit 1
esac

exit 0
	
